language: node_js
dist: trusty
sudo: false
node_js:
- '8'
before_install:
- cd src
script:
- npm test --silent
notifications:
  slack:
    secure: ZKZcs8CKKXk2soU5VF7Z1u37DFzqutLflYqmElp/4DekOzAL3u65iNsWM4yewCbY4afgVxvHV7ESP31UiXlTQruki8pytRagTjiR0cUxVS5GAbth41rjbqLUl0yF3v4F3pR8azbpSpUt2drZVLE8P3RNZp2UtqOuQwPO57NPSR7FhSNbtLn7pvyBlUexL2T7jmSSixEHUp4GlfZwJ1atosLp5ZXYSMVUGHU/xs3e9DHrNG3mr4swjVhzzmb50PIpwxOh4zodPNq7niT7CLspMQA5P3+8Vjcm3GtkSJmI8WwWaHjbTYPRJWYAa4Gm6WLwWEakaR1NvAAZ0ZjZCUuzB4+ZFm15Vdrm2MzVJZ9UvCP14snWgSfwYUWn//oYii4KDR29wTofYIqxAiA8MqRTLVq3ERHZ8iYZn5coaE9cY8px0+eekP5OwLA8KzILXiiSIuJM7EjfOP6lGTSvgWZcnO5ymA0S7ZxCqRbOK8FOXXtcQg4LB8Qd6ALGmRW9dcQJyLaJrmrABefmJxf13xuqoVXxN5PBL5asUNVb8TIHdFKqr4Uga+z94M1p0xE9AttbbY0169+4Oe33ZNTaU2t9/RBDEGGKYUTnsOfmWIQ/Xr1zECcrsFQ0MsEs//Y+O9NCffzEjWUpQAeCAC+Bi7dmEKdT9YJF4Vpb3ULESMDiYOE=
